AllCops:
  NewCops: enable
  Exclude:
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  SuggestExtensions: false

Style/ClassAndModuleChildren:
  Enabled: false
Layout/LineLength:
  Max: 100
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/MethodLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/ParameterLists:
  Max: 6
Metrics/ClassLength:
  Max: 250
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 100
Metrics/PerceivedComplexity:
  Max: 20
Style/MultilineTernaryOperator:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
