docker:
  image: yegor256/rultor-image:1.9.1
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  script: |-
    bundle exec rake clean test rubocop copyright
    sed -i "s/0\.0\.0/${tag}/g" lib/sibit/version.rb
    git add lib/sibit/version.rb
    git commit -m "version set to ${tag}"
    gem build sibit.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake clean test rubocop copyright
